version: 2
jobs:
  build:
    docker:
      - image: cimg/node:20.2.0-browsers

    working_directory: ~/youtube-history-extension

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          
          # fall back to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install your dependencies
      - run: yarn install
      # Install additional dependencies
      - run: yarn add puppeteer mocha -D

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # build the extension if required
      # Run our test suite 
      - run: yarn test
